development:
  adapter: postgresql
  encoding: unicode
  database: stellar_development
  pool: 5
  username: MOOKBOOK13
  password:
  host: localhost
  port: 5432

  production:
  adapter: postgresql
  encoding: unicode
  database: stellar_production
  pool: 5
  password:
